/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
File Name:	Game.java
Programmer:	Esha Haque
Date:		July 26, 2021
Description:	This program is a game of Dots and Boxes, this file being the
*               gameplay portion of the application. Players take turns
*               connecting dots vertically and horizontally to complete boxes on
*               the grid. When a player completed a box, they gain a point and
*               continue their turn. The player with the most boxes cleared by
*               the end of the game, when the grid is filled, is the winner.
*/

package dotsandboxes;
import java.awt.*;
import javax.swing.*;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import dotsandboxes.Start;
/**
 *
 * @author Esha
 */
public class Game extends javax.swing.JFrame {
    //Variables carried over from Start Frame
    static String [] outList;
    static String PlayerA = Start.PlayerA; //Player A's name
    static String PlayerB = Start.PlayerB; //Player B's name
    static int ScoreA = Start.ScoreA; //Player A's total score
    static int ScoreB = Start.ScoreB; //Player B's total score
    //Game variables
    int turn = 0; //Turn counter
    boolean redTurn = true;
    static String winner; //Winner's username at end of game
    int scoreRed = 0; //Boxes cleared by red
    int scoreBlue = 0; //Boxes cleared by blue
    int boxes[] = new int [13]; //Each element represents a box. The number
    // (0-4) is number of lines around it completed. 4 means box is cleared.
    int lines[] = new int [31];
    //Image icons
    ImageIcon rh = new ImageIcon("horizontalRed.jpg");
    ImageIcon bh = new ImageIcon("horizontalBlue.jpg");
    ImageIcon rv = new ImageIcon("verticalRed.jpg");
    ImageIcon bv = new ImageIcon("verticalBlue.jpg");
    ImageIcon iconR = new ImageIcon("iconRed.jpg");
    ImageIcon iconB = new ImageIcon("iconBlue.jpg");
    
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        //Set Player stat displays
        
        txtRedName.setText("Player 1's Turn");
        txtBlueName.setText("");
        txtRedScore.setText(String.valueOf(scoreRed));
        txtBlueScore.setText(String.valueOf(scoreBlue));
        //Background colour
        Color bg = new Color(255, 255, 255);
        getContentPane().setBackground(bg);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h1 = new javax.swing.JButton();
        v1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        h2 = new javax.swing.JButton();
        v2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        h3 = new javax.swing.JButton();
        v3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        h4 = new javax.swing.JButton();
        v4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        v5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        h7 = new javax.swing.JButton();
        v8 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        h8 = new javax.swing.JButton();
        v9 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        v10 = new javax.swing.JButton();
        h5 = new javax.swing.JButton();
        v6 = new javax.swing.JButton();
        b6 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        h6 = new javax.swing.JButton();
        v7 = new javax.swing.JButton();
        h11 = new javax.swing.JButton();
        h10 = new javax.swing.JButton();
        v14 = new javax.swing.JButton();
        v12 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        v11 = new javax.swing.JButton();
        b11 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        h9 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        v13 = new javax.swing.JButton();
        h12 = new javax.swing.JButton();
        v15 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        h13 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        h14 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        h15 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        h16 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRedName = new javax.swing.JTextField();
        txtRedScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBlueName = new javax.swing.JTextField();
        txtBlueScore = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        h1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });

        v1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/iconBlue.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/iconRed.jpg"))); // NOI18N

        b1.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        b2.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });

        v2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        b3.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        h3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });

        v3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        b4.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        h4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h4ActionPerformed(evt);
            }
        });

        v4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v4ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        v5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v5ActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        b7.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        h7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h7ActionPerformed(evt);
            }
        });

        v8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v8ActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        b8.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        h8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h8ActionPerformed(evt);
            }
        });

        v9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v9ActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        b5.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        v10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v10ActionPerformed(evt);
            }
        });

        h5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h5ActionPerformed(evt);
            }
        });

        v6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v6ActionPerformed(evt);
            }
        });

        b6.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        h6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h6ActionPerformed(evt);
            }
        });

        v7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v7ActionPerformed(evt);
            }
        });

        h11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h11ActionPerformed(evt);
            }
        });

        h10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h10ActionPerformed(evt);
            }
        });

        v14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v14ActionPerformed(evt);
            }
        });

        v12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v12ActionPerformed(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        v11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v11ActionPerformed(evt);
            }
        });

        b11.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        b9.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        b12.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        h9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h9ActionPerformed(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        b10.setIcon(new javax.swing.ImageIcon("C:\\Users\\eshah\\Documents\\NetBeansProjects\\dotsAndBoxes\\iconBlank.jpg")); // NOI18N

        v13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v13ActionPerformed(evt);
            }
        });

        h12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h12ActionPerformed(evt);
            }
        });

        v15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/verticalGrey.jpg"))); // NOI18N
        v15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v15ActionPerformed(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        h13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h13ActionPerformed(evt);
            }
        });

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        h14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h14ActionPerformed(evt);
            }
        });

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        h15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h15ActionPerformed(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        h16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/horizontalGrey.jpg"))); // NOI18N
        h16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h16ActionPerformed(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dotsandboxes/dot.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Dots and Boxes");

        txtRedName.setEditable(false);

        txtRedScore.setEditable(false);

        jLabel5.setText("Boxes Cleared:");

        txtBlueName.setEditable(false);

        txtBlueScore.setEditable(false);

        jLabel7.setText("Boxes Cleared:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(9, 9, 9))
                            .addComponent(jLabel1)
                            .addComponent(jLabel27))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel19)
                                    .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(v8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel35)
                                    .addComponent(v13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(v9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(v14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(b12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(h12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel24)
                                    .addComponent(v10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)
                                    .addComponent(v15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(h13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38)
                                .addGap(12, 12, 12)
                                .addComponent(h14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel39)
                                .addGap(12, 12, 12)
                                .addComponent(h15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel40)
                                .addGap(12, 12, 12)
                                .addComponent(h16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel41))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRedName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRedScore)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBlueScore, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBlueName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(305, 305, 305))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(h1)
                        .addGap(18, 18, 18)
                        .addComponent(b1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(h2)
                        .addGap(18, 18, 18)
                        .addComponent(b2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(h3)
                        .addGap(18, 18, 18)
                        .addComponent(b3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(h4)
                        .addGap(18, 18, 18)
                        .addComponent(b4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h5)
                                .addGap(18, 18, 18)
                                .addComponent(b5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h6)
                                .addGap(18, 18, 18)
                                .addComponent(b6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h7)
                                .addGap(18, 18, 18)
                                .addComponent(b7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h8)
                                .addGap(18, 18, 18)
                                .addComponent(b8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h9)
                                .addGap(18, 18, 18)
                                .addComponent(b9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h10)
                                .addGap(18, 18, 18)
                                .addComponent(b10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h11)
                                .addGap(18, 18, 18)
                                .addComponent(b11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(h12)
                                .addGap(18, 18, 18)
                                .addComponent(b12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h13)
                    .addComponent(h14)
                    .addComponent(jLabel38)
                    .addComponent(h15)
                    .addComponent(jLabel39)
                    .addComponent(h16)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBlueName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBlueScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRedScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
        if (lines[0] == 0){ //Make sure this line has not been clicked before
            line(false, 1, 1, b1, b1, h1); //Line click actions
        }
        lines[0] ++; //Line has been clicked
    }//GEN-LAST:event_h1ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:
        if (lines[1] == 0){ //Make sure this line has not been clicked before
            line(false, 2, 2, b2, b2, h2); //Line click actions
        }
        lines[1] ++; //Line has been clicked
    }//GEN-LAST:event_h2ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:
        if (lines[2] == 0){ //Make sure this line has not been clicked before
            line(false, 3, 3, b3, b3, h3); //Line click actions
        }
        lines[2] ++; //Line has been clicked
    }//GEN-LAST:event_h3ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h4ActionPerformed
        // TODO add your handling code here:
        if (lines[3] == 0){ //Make sure this line has not been clicked before
            line(false, 4, 4, b4, b4, h4); //Line click actions
        }
        lines[3] ++; //Line has been clicked
    }//GEN-LAST:event_h4ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h5ActionPerformed
        // TODO add your handling code here:
        if (lines[4] == 0){ //Make sure this line has not been clicked before
            line(false, 1, 5, b1, b5, h5); //Line click actions
        }
        lines[4] ++; //Line has been clicked
    }//GEN-LAST:event_h5ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h6ActionPerformed
        // TODO add your handling code here:
        if (lines[5] == 0){ //Make sure this line has not been clicked before
            line(false, 2, 6, b2, b6, h6); //Line click actions
        }
        lines[5] ++; //Line has been clicked
    }//GEN-LAST:event_h6ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h7ActionPerformed
        // TODO add your handling code here:
        if (lines[6] == 0){ //Make sure this line has not been clicked before
            line(false, 3, 7, b3, b7, h7); //Line click actions
        }
        lines[6] ++; //Line has been clicked
    }//GEN-LAST:event_h7ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h8ActionPerformed
        // TODO add your handling code here:
        if (lines[7] == 0){ //Make sure this line has not been clicked before
            line(false, 4, 8, b4, b8, h8); //Line click actions
        }
        lines[7] ++; //Line has been clicked
    }//GEN-LAST:event_h8ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h9ActionPerformed
        // TODO add your handling code here:
        if (lines[8] == 0){ //Make sure this line has not been clicked before
            line(false, 5, 9, b5, b9, h9); //Line click actions
        }
        lines[8] ++; //Line has been clicked
    }//GEN-LAST:event_h9ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h10ActionPerformed
        // TODO add your handling code here:
        if (lines[9] == 0){ //Make sure this line has not been clicked before
            line(false, 6, 10, b6, b10, h10); //Line click actions
        }
        lines[9] ++; //Line has been clicked
    }//GEN-LAST:event_h10ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h11ActionPerformed
        // TODO add your handling code here:
        if (lines[10] == 0){ //Make sure this line has not been clicked before
            line(false, 7, 11, b7, b11, h11); //Line click actions
        }
        lines[10] ++; //Line has been clicked
    }//GEN-LAST:event_h11ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h12ActionPerformed
        // TODO add your handling code here:
        if (lines[11] == 0){ //Make sure this line has not been clicked before
            line(false, 8, 12, b8, b12, h12); //Line click actions
        }
        lines[11] ++; //Line has been clicked
    }//GEN-LAST:event_h12ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h13ActionPerformed
        // TODO add your handling code here:
        if (lines[12] == 0){ //Make sure this line has not been clicked before
            line(false, 9, 9, b9, b9, h13); //Line click actions
        }
        lines[12] ++; //Line has been clicked
    }//GEN-LAST:event_h13ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h14ActionPerformed
        // TODO add your handling code here:
        if (lines[13] == 0){ //Make sure this line has not been clicked before
            line(false, 10, 10, b10, b10, h14); //Line click actions
        }
        lines[13] ++; //Line has been clicked
    }//GEN-LAST:event_h14ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h15ActionPerformed
        // TODO add your handling code here:
        if (lines[14] == 0){ //Make sure this line has not been clicked before
            line(false, 11, 11, b11, b11, h15); //Line click actions
        }
        lines[14] ++; //Line has been clicked
    }//GEN-LAST:event_h15ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void h16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h16ActionPerformed
        // TODO add your handling code here:
        if (lines[15] == 0){ //Make sure this line has not been clicked before
            line(false, 12, 12, b12, b12, h16); //Line click actions
        }
        lines[15] ++; //Line has been clicked
    }//GEN-LAST:event_h16ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        // TODO add your handling code here:
        if (lines[16] == 0){ //Make sure this line has not been clicked before
            line(true, 1, 1, b1, b1, v1); //Line click actions
        }
        lines[16] ++; //Line has been clicked
    }//GEN-LAST:event_v1ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2ActionPerformed
        // TODO add your handling code here:
        if (lines[17] == 0){ //Make sure this line has not been clicked before
            line(true, 1, 2, b1, b2, v2); //Line click actions
        }
        lines[17] ++; //Line has been clicked
    }//GEN-LAST:event_v2ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed
        // TODO add your handling code here:
        if (lines[18] == 0){ //Make sure this line has not been clicked before
            line(true, 2, 3, b2, b3, v3); //Line click actions
        }
        lines[18] ++; //Line has been clicked
    }//GEN-LAST:event_v3ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v4ActionPerformed
        // TODO add your handling code here:
        if (lines[19] == 0){ //Make sure this line has not been clicked before
            line(true, 3, 4, b3, b4, v4); //Line click actions
        }
        lines[19] ++; //Line has been clicked
    }//GEN-LAST:event_v4ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v5ActionPerformed
        // TODO add your handling code here:
        if (lines[20] == 0){ //Make sure this line has not been clicked before
            line(true, 4, 4, b4, b4, v5); //Line click actions
        }
        lines[20] ++; //Line has been clicked
    }//GEN-LAST:event_v5ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v6ActionPerformed
        // TODO add your handling code here:
        if (lines[21] == 0){ //Make sure this line has not been clicked before
            line(true, 5, 5, b5, b5, v6); //Line click actions
        }
        lines[21] ++; //Line has been clicked
    }//GEN-LAST:event_v6ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v7ActionPerformed
        // TODO add your handling code here:
        if (lines[22] == 0){ //Make sure this line has not been clicked before
            line(true, 5, 6, b5, b6, v7); //Line click actions
        }
        lines[22] ++; //Line has been clicked
    }//GEN-LAST:event_v7ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v8ActionPerformed
        // TODO add your handling code here:
        if (lines[23] == 0){ //Make sure this line has not been clicked before
            line(true, 6, 7, b6, b7, v8); //Line click actions
        }
        lines[23] ++; //Line has been clicked
    }//GEN-LAST:event_v8ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v9ActionPerformed
        // TODO add your handling code here:
        if (lines[24] == 0){ //Make sure this line has not been clicked before
            line(true, 7, 8, b7, b8, v9); //Line click actions
        }
        lines[24] ++; //Line has been clicked
    }//GEN-LAST:event_v9ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v10ActionPerformed
        // TODO add your handling code here:
        if (lines[25] == 0){ //Make sure this line has not been clicked before
            line(true, 8, 8, b8, b8, v10); //Line click actions
        }
        lines[25] ++; //Line has been clicked
    }//GEN-LAST:event_v10ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v11ActionPerformed
        // TODO add your handling code here:
        if (lines[26] == 0){ //Make sure this line has not been clicked before
            line(true, 9, 9, b9, b9, v11); //Line click actions
        }
        lines[26] ++; //Line has been clicked
    }//GEN-LAST:event_v11ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v12ActionPerformed
        // TODO add your handling code here:
        if (lines[27] == 0){ //Make sure this line has not been clicked before
            line(true, 9, 10, b9, b10, v12); //Line click actions
        }
        lines[27] ++; //Line has been clicked
    }//GEN-LAST:event_v12ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v13ActionPerformed
        // TODO add your handling code here:
        if (lines[28] == 0){ //Make sure this line has not been clicked before
            line(true, 10, 11, b10, b11, v13); //Line click actions
        }
        lines[28] ++; //Line has been clicked
    }//GEN-LAST:event_v13ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v14ActionPerformed
        // TODO add your handling code here:
        if (lines[29] == 0){ //Make sure this line has not been clicked before
            line(true, 11, 12, b11, b12, v14); //Line click actions
        }
        lines[29] ++; //Line has been clicked
    }//GEN-LAST:event_v14ActionPerformed
/**
 * 
 * @param evt When this line button is clicked.
 * If this line has not already been selected, select it and add a side to
 * the boxes it is part of.
 */
    private void v15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v15ActionPerformed
        // TODO add your handling code here:
        if (lines[30] == 0){ //Make sure this line has not been clicked before
            line(true, 12, 12, b12, b12, v15); //Line click actions
        }
        lines[30] ++; //Line has been clicked
    }//GEN-LAST:event_v15ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(false);
            }
        });
        new Start().setVisible(true); //Set next frame visible
        //READING
        //Read through file and place each line into the array outList
        ArrayList <String> txtList = new ArrayList <String>();
        BufferedReader br = null;

        try {
            br = new BufferedReader(new FileReader("Scores.txt"));
            String word;
            while ((word = br.readLine()) != null ){
                txtList.add(word);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

        outList = new String[txtList.size()];
        txtList.toArray(outList);
        /*
        for (int i = 0; i < outList.length; i++){
            System.out.println(outList[i]);
        }
        */
        
        
    }
    
    /**
     * 
     * @param vertical Whether or not the line is vertical (otherwise horizontal)
     * Each line is part of 1-2 boxes. If there's only one, boxB = boxA
     * @param boxIndexA Index of first box's array position for tracking box completion
     * @param boxIndexB Index of second box's array position for tracking box completion
     * @param boxA First box's JLabel
     * @param boxB Second box's JLabel
     * @param self The selected line's JButton
     * Change the icon of the line to an icon with the same orientation and the
     * colour of the player whose turn it was. For every box that is completed,
     * change the box's icon to that of the player who completed the box and
     * update the player's score to match the number of boxes they have cleared.
     * Switch to the next player's turn if a box was not completed in this turn;
     * otherwise, if the player has completed a box, continue their turn.
     */
    public void line (boolean vertical, int boxIndexA, int boxIndexB, JLabel boxA, JLabel boxB, JButton self){
        boolean boxCleared = false; //Whether or not a box has been cleared in this turn
        //Turn counter to track the end of the game
        if (boxes[boxIndexA] < 4 || boxes[boxIndexB] < 4){
            turn ++;
        }
        //Box a
        if (boxes[boxIndexA] < 4){ //Box not yet cleared
            boxes[boxIndexA] ++; //Add to box's line counter
            //Set icon of line to the right orientation/colour
            if (redTurn){ //Red's turn
                if (vertical){ //Vertical line
                    self.setIcon(rv);
                }else{ //Horizontal Line
                    self.setIcon(rh);
                }
            }else{ //Blue's turn
                if (vertical){ //Vertical line
                    self.setIcon(bv);
                }else{ //Horizontal Line
                    self.setIcon(bh);
                }
            }
            if (boxes[boxIndexA] == 4){ //Box cleared
                //Set icon of box according to current turn
                if (redTurn){ //Red's turn
                    boxA.setIcon(iconR);
                    boxCleared = true;
                    scoreRed ++; //Score increase
                }else{ //Blue's turn
                    boxA.setIcon(iconB);
                    boxCleared = true;
                    scoreBlue++; //Score increase
                }
            }
        }
        //Box b
        if (boxA != boxB && boxes[boxIndexB] < 4){ //Box not yet cleared
            boxes[boxIndexB] ++; //Add to box's line counter
            //Set icon of line to the right orientation/colour
            if (redTurn){ //Red's turn
                if (vertical){ //Vertical line
                    self.setIcon(rv);
                }else{ //Horizontal Line
                    self.setIcon(rh);
                }
            }else{ //Blue's turn
                if (vertical){ //Vertical line
                    self.setIcon(bv);
                }else{ //Horizontal Line
                    self.setIcon(bh);
                }
            }
            if (boxes[boxIndexB] == 4){ //Box cleared
                //Set icon of box according to current turn
                if (redTurn){ //Red's turn
                    boxB.setIcon(iconR);
                    boxCleared = true;
                    scoreRed ++; //Score increase
                }else{ //Blue's turn
                    boxB.setIcon(iconB);
                    boxCleared = true;
                    scoreBlue++; //Score increase
                }
            }
        }
        // Update score display
        txtRedScore.setText(String.valueOf(scoreRed));
        txtBlueScore.setText(String.valueOf(scoreBlue));
        //Next player's turn, unless last player cleared a box and continues theirs
        if (!boxCleared){
            if (redTurn){
                redTurn = false;
            }else{
                redTurn = true;
            }
        }
        //Update Turn display
        if (redTurn){
            txtRedName.setText(PlayerA + "'s turn");
            txtBlueName.setText(PlayerB);
        }else{
            txtRedName.setText(PlayerA);
            txtBlueName.setText(PlayerB + "'s turn");
        }
        //Game over
        if (turn == 31){
            if (scoreRed > scoreBlue){ //Red won
                winner = PlayerA;
                ScoreA += scoreRed; //Increase leaderboard score
            }else if (scoreBlue > scoreRed){ //Blue won
                winner = PlayerB;
                ScoreB += scoreBlue; //Increase leaderboard score
            }else{ //Tie
                winner = "It's a tie!";
                ScoreA += scoreRed; //Increase leaderboard score
                ScoreB += scoreBlue; //Increase leaderboard score
            }
            //this.setVisible(false); //Set this frame invisible
            //Open Game Over Frame here
            new GameOver().setVisible(true); //Set next frame visible
            this.setVisible(false); //Set this frame invisible
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JButton h1;
    private javax.swing.JButton h10;
    private javax.swing.JButton h11;
    private javax.swing.JButton h12;
    private javax.swing.JButton h13;
    private javax.swing.JButton h14;
    private javax.swing.JButton h15;
    private javax.swing.JButton h16;
    private javax.swing.JButton h2;
    private javax.swing.JButton h3;
    private javax.swing.JButton h4;
    private javax.swing.JButton h5;
    private javax.swing.JButton h6;
    private javax.swing.JButton h7;
    private javax.swing.JButton h8;
    private javax.swing.JButton h9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBlueName;
    private javax.swing.JTextField txtBlueScore;
    private javax.swing.JTextField txtRedName;
    private javax.swing.JTextField txtRedScore;
    private javax.swing.JButton v1;
    private javax.swing.JButton v10;
    private javax.swing.JButton v11;
    private javax.swing.JButton v12;
    private javax.swing.JButton v13;
    private javax.swing.JButton v14;
    private javax.swing.JButton v15;
    private javax.swing.JButton v2;
    private javax.swing.JButton v3;
    private javax.swing.JButton v4;
    private javax.swing.JButton v5;
    private javax.swing.JButton v6;
    private javax.swing.JButton v7;
    private javax.swing.JButton v8;
    private javax.swing.JButton v9;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param rv Image to be set as an icon
     * Set the icon image for a GUI component
     */
    private void setIcon(ImageIcon rv) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
