/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dotsandboxes;
import java.awt.Color;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.*;
import dotsandboxes.Game;
/**
 *
 * @author Esha
 */
public class Start extends javax.swing.JFrame {
    // Variables for Player Data
    static String PlayerA = "";
    static String PlayerB = "";
    static int ScoreA;
    static int ScoreB;
    boolean setA = false;
    boolean setB = false;
    int newLine = 0;
    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        //Background colour
        Color bg = new Color(94, 92, 178);
        getContentPane().setBackground(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        btnPlay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNameA = new javax.swing.JTextField();
        btnAddA = new javax.swing.JButton();
        txtNameB = new javax.swing.JTextField();
        btnAddB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(94, 92, 178));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 248, 248));
        jLabel3.setText("Player 1:");

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(248, 248, 248));
        jLabel4.setText("Player 2:");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        btnPlay.setText("Play!");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 248, 248));
        jLabel6.setText("Dots and Boxes");

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 248, 248));
        jLabel1.setText("Enter Player Names:");

        btnAddA.setText("Add");
        btnAddA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAActionPerformed(evt);
            }
        });

        btnAddB.setText("Add");
        btnAddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNameA)
                                            .addComponent(txtNameB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAddA)
                                            .addComponent(btnAddB)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnPlay)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddA)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddB)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPlay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        //Move on to Game Frame
        if (setA && setB){
            new Game().setVisible(true); //Set next frame visible
            this.setVisible(false); //Set this frame invisible
            Game.PlayerA = Start.PlayerA; //Player A's name
            Game.PlayerB = Start.PlayerB; //Player B's name
            Game.ScoreA = Start.ScoreA; //Player A's total score
            Game.ScoreB = Start.ScoreB; //Player B's total score
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnAddAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAActionPerformed
        // TODO add your handling code here:
        PlayerA = txtNameA.getText(); //Entered Name
        boolean inFile = false;
        for (int i = 0; i < Game.outList.length - 1; i++){
            if (PlayerA.equals(Game.outList[i])){ //Find Player Record
                inFile = true;
                ScoreA = Integer.parseInt(Game.outList[i+1]);
            }
        }
        if (!inFile){ //Create new player record if it doesn't exist
            newLine++;
            ScoreA = 0;
            //WRITING
            try {
                Files.write(Paths.get("Scores.txt"), ("\n"+PlayerA).getBytes(), StandardOpenOption.APPEND);
            }catch (IOException e) {
            }
            try {
                Files.write(Paths.get("Scores.txt"), ("\n0").getBytes(), StandardOpenOption.APPEND);
            }catch (IOException e) {
            }
        }
        setA = true;

        //Display Players and their totals
        if (setA && setB){
            String output = "Players:\n\n";
            output += PlayerA + ", score: " + ScoreA + "\n";
            output += PlayerB + ", score: " + ScoreB + "\n";
            txtOutput.setText(output);
        }
    }//GEN-LAST:event_btnAddAActionPerformed

    private void btnAddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBActionPerformed
        // TODO add your handling code here:
        PlayerB = txtNameB.getText(); //Entered Name
        boolean inFile = false;
        for (int i = 0; i < Game.outList.length - 1; i++){
            if (PlayerB.equals(Game.outList[i])){ //Find Player Record
                inFile = true;
                ScoreB = Integer.parseInt(Game.outList[i+1]);
            }
        }
        if (!inFile){ //Create new player record if it doesn't exist
            newLine++;
            ScoreB = 0;
            //WRITING
            try {
                Files.write(Paths.get("Scores.txt"), ("\n"+PlayerB).getBytes(), StandardOpenOption.APPEND);
            }catch (IOException e) {
            }
            try {
                Files.write(Paths.get("Scores.txt"), ("\n0").getBytes(), StandardOpenOption.APPEND);
            }catch (IOException e) {
            }
        }
        setB = true;

        if (setA && setB){
            String output = "Players:\n\n";
            output += PlayerA + ", score: " + ScoreA + "\n";
            output += PlayerB + ", score: " + ScoreB + "\n";
            txtOutput.setText(output);
        }
    }//GEN-LAST:event_btnAddBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
        //READING
        //Read through file and place each line into the array outList
        ArrayList <String> txtList = new ArrayList <String>();
        BufferedReader br = null;

        try {
            br = new BufferedReader(new FileReader("Scores.txt"));
            String word;
            while ((word = br.readLine()) != null ){
                txtList.add(word);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

        Game.outList = new String[txtList.size()];
        txtList.toArray(Game.outList);
        /*
        for (int i = 0; i < Game.outList.length; i++){
            System.out.println(Game.outList[i]);
        }
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddA;
    private javax.swing.JButton btnAddB;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNameA;
    private javax.swing.JTextField txtNameB;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
